/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUsersRouteImport } from './routes/app.users'
import { Route as AppTrackingRouteImport } from './routes/app.tracking'
import { Route as AppReviewQueueRouteImport } from './routes/app.review-queue'
import { Route as AppPromptsRouteImport } from './routes/app.prompts'
import { Route as AppOutputsRouteImport } from './routes/app.outputs'
import { Route as AppNewCaseRouteImport } from './routes/app.new-case'
import { Route as AppMinhasVistoriasRouteImport } from './routes/app.minhas-vistorias'
import { Route as AppHistoryRouteImport } from './routes/app.history'
import { Route as AppFormsAssistantRouteImport } from './routes/app.forms-assistant'
import { Route as AppFormsRouteImport } from './routes/app.forms'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppConfiguracoesRouteImport } from './routes/app.configuracoes'
import { Route as AppClientsRouteImport } from './routes/app.clients'
import { Route as AppCatalogoMateriaisRouteImport } from './routes/app.catalogo-materiais'
import { Route as AppCasesRouteImport } from './routes/app.cases'
import { Route as AppBaseConhecimentoRouteImport } from './routes/app.base-conhecimento'
import { Route as AppAgentePerfilRouteImport } from './routes/app.agente-perfil'
import { Route as AppAgenteIaRouteImport } from './routes/app.agente-ia'
import { Route as AppAgendaRouteImport } from './routes/app.agenda'
import { Route as ApiVistoriaChatRouteImport } from './routes/api/vistoria-chat'
import { Route as ApiFormsAssistantRouteImport } from './routes/api/forms-assistant'
import { Route as ApiAgenteIaRouteImport } from './routes/api/agente-ia'
import { Route as AgentTokenRouteImport } from './routes/agent.$token'
import { Route as AppFormsIndexRouteImport } from './routes/app.forms.index'
import { Route as AppClientsIndexRouteImport } from './routes/app.clients.index'
import { Route as PreviewFormsIdRouteImport } from './routes/preview.forms.$id'
import { Route as AppVistoriasIdRouteImport } from './routes/app.vistorias.$id'
import { Route as AppVistoriaCasoIdRouteImport } from './routes/app.vistoria.$casoId'
import { Route as AppReviewIdRouteImport } from './routes/app.review.$id'
import { Route as AppClientsEmpresaIdRouteImport } from './routes/app.clients.$empresaId'
import { Route as AppAgendamentoIdRouteImport } from './routes/app.agendamento.$id'
import { Route as AppFormsIdIndexRouteImport } from './routes/app.forms.$id.index'
import { Route as AppFormsIdPreviewRouteImport } from './routes/app.forms.$id.preview'
import { Route as ApiPublicHooksCheckAtrasosRouteImport } from './routes/api/public/hooks/check-atrasos'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppTrackingRoute = AppTrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewQueueRoute = AppReviewQueueRouteImport.update({
  id: '/review-queue',
  path: '/review-queue',
  getParentRoute: () => AppRoute,
} as any)
const AppPromptsRoute = AppPromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => AppRoute,
} as any)
const AppOutputsRoute = AppOutputsRouteImport.update({
  id: '/outputs',
  path: '/outputs',
  getParentRoute: () => AppRoute,
} as any)
const AppNewCaseRoute = AppNewCaseRouteImport.update({
  id: '/new-case',
  path: '/new-case',
  getParentRoute: () => AppRoute,
} as any)
const AppMinhasVistoriasRoute = AppMinhasVistoriasRouteImport.update({
  id: '/minhas-vistorias',
  path: '/minhas-vistorias',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppFormsAssistantRoute = AppFormsAssistantRouteImport.update({
  id: '/forms-assistant',
  path: '/forms-assistant',
  getParentRoute: () => AppRoute,
} as any)
const AppFormsRoute = AppFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsRoute = AppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogoMateriaisRoute = AppCatalogoMateriaisRouteImport.update({
  id: '/catalogo-materiais',
  path: '/catalogo-materiais',
  getParentRoute: () => AppRoute,
} as any)
const AppCasesRoute = AppCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => AppRoute,
} as any)
const AppBaseConhecimentoRoute = AppBaseConhecimentoRouteImport.update({
  id: '/base-conhecimento',
  path: '/base-conhecimento',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentePerfilRoute = AppAgentePerfilRouteImport.update({
  id: '/agente-perfil',
  path: '/agente-perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppAgenteIaRoute = AppAgenteIaRouteImport.update({
  id: '/agente-ia',
  path: '/agente-ia',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendaRoute = AppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AppRoute,
} as any)
const ApiVistoriaChatRoute = ApiVistoriaChatRouteImport.update({
  id: '/api/vistoria-chat',
  path: '/api/vistoria-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFormsAssistantRoute = ApiFormsAssistantRouteImport.update({
  id: '/api/forms-assistant',
  path: '/api/forms-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgenteIaRoute = ApiAgenteIaRouteImport.update({
  id: '/api/agente-ia',
  path: '/api/agente-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentTokenRoute = AgentTokenRouteImport.update({
  id: '/agent/$token',
  path: '/agent/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppFormsIndexRoute = AppFormsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppFormsRoute,
} as any)
const AppClientsIndexRoute = AppClientsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppClientsRoute,
} as any)
const PreviewFormsIdRoute = PreviewFormsIdRouteImport.update({
  id: '/preview/forms/$id',
  path: '/preview/forms/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVistoriasIdRoute = AppVistoriasIdRouteImport.update({
  id: '/vistorias/$id',
  path: '/vistorias/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppVistoriaCasoIdRoute = AppVistoriaCasoIdRouteImport.update({
  id: '/vistoria/$casoId',
  path: '/vistoria/$casoId',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewIdRoute = AppReviewIdRouteImport.update({
  id: '/review/$id',
  path: '/review/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsEmpresaIdRoute = AppClientsEmpresaIdRouteImport.update({
  id: '/$empresaId',
  path: '/$empresaId',
  getParentRoute: () => AppClientsRoute,
} as any)
const AppAgendamentoIdRoute = AppAgendamentoIdRouteImport.update({
  id: '/agendamento/$id',
  path: '/agendamento/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppFormsIdIndexRoute = AppFormsIdIndexRouteImport.update({
  id: '/$id/',
  path: '/$id/',
  getParentRoute: () => AppFormsRoute,
} as any)
const AppFormsIdPreviewRoute = AppFormsIdPreviewRouteImport.update({
  id: '/$id/preview',
  path: '/$id/preview',
  getParentRoute: () => AppFormsRoute,
} as any)
const ApiPublicHooksCheckAtrasosRoute =
  ApiPublicHooksCheckAtrasosRouteImport.update({
    id: '/api/public/hooks/check-atrasos',
    path: '/api/public/hooks/check-atrasos',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/agent/$token': typeof AgentTokenRoute
  '/api/agente-ia': typeof ApiAgenteIaRoute
  '/api/forms-assistant': typeof ApiFormsAssistantRoute
  '/api/vistoria-chat': typeof ApiVistoriaChatRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/agente-ia': typeof AppAgenteIaRoute
  '/app/agente-perfil': typeof AppAgentePerfilRoute
  '/app/base-conhecimento': typeof AppBaseConhecimentoRoute
  '/app/cases': typeof AppCasesRoute
  '/app/catalogo-materiais': typeof AppCatalogoMateriaisRoute
  '/app/clients': typeof AppClientsRouteWithChildren
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/forms': typeof AppFormsRouteWithChildren
  '/app/forms-assistant': typeof AppFormsAssistantRoute
  '/app/history': typeof AppHistoryRoute
  '/app/minhas-vistorias': typeof AppMinhasVistoriasRoute
  '/app/new-case': typeof AppNewCaseRoute
  '/app/outputs': typeof AppOutputsRoute
  '/app/prompts': typeof AppPromptsRoute
  '/app/review-queue': typeof AppReviewQueueRoute
  '/app/tracking': typeof AppTrackingRoute
  '/app/users': typeof AppUsersRoute
  '/app/agendamento/$id': typeof AppAgendamentoIdRoute
  '/app/clients/$empresaId': typeof AppClientsEmpresaIdRoute
  '/app/review/$id': typeof AppReviewIdRoute
  '/app/vistoria/$casoId': typeof AppVistoriaCasoIdRoute
  '/app/vistorias/$id': typeof AppVistoriasIdRoute
  '/preview/forms/$id': typeof PreviewFormsIdRoute
  '/app/clients/': typeof AppClientsIndexRoute
  '/app/forms/': typeof AppFormsIndexRoute
  '/api/public/hooks/check-atrasos': typeof ApiPublicHooksCheckAtrasosRoute
  '/app/forms/$id/preview': typeof AppFormsIdPreviewRoute
  '/app/forms/$id/': typeof AppFormsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/agent/$token': typeof AgentTokenRoute
  '/api/agente-ia': typeof ApiAgenteIaRoute
  '/api/forms-assistant': typeof ApiFormsAssistantRoute
  '/api/vistoria-chat': typeof ApiVistoriaChatRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/agente-ia': typeof AppAgenteIaRoute
  '/app/agente-perfil': typeof AppAgentePerfilRoute
  '/app/base-conhecimento': typeof AppBaseConhecimentoRoute
  '/app/cases': typeof AppCasesRoute
  '/app/catalogo-materiais': typeof AppCatalogoMateriaisRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/forms-assistant': typeof AppFormsAssistantRoute
  '/app/history': typeof AppHistoryRoute
  '/app/minhas-vistorias': typeof AppMinhasVistoriasRoute
  '/app/new-case': typeof AppNewCaseRoute
  '/app/outputs': typeof AppOutputsRoute
  '/app/prompts': typeof AppPromptsRoute
  '/app/review-queue': typeof AppReviewQueueRoute
  '/app/tracking': typeof AppTrackingRoute
  '/app/users': typeof AppUsersRoute
  '/app/agendamento/$id': typeof AppAgendamentoIdRoute
  '/app/clients/$empresaId': typeof AppClientsEmpresaIdRoute
  '/app/review/$id': typeof AppReviewIdRoute
  '/app/vistoria/$casoId': typeof AppVistoriaCasoIdRoute
  '/app/vistorias/$id': typeof AppVistoriasIdRoute
  '/preview/forms/$id': typeof PreviewFormsIdRoute
  '/app/clients': typeof AppClientsIndexRoute
  '/app/forms': typeof AppFormsIndexRoute
  '/api/public/hooks/check-atrasos': typeof ApiPublicHooksCheckAtrasosRoute
  '/app/forms/$id/preview': typeof AppFormsIdPreviewRoute
  '/app/forms/$id': typeof AppFormsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/agent/$token': typeof AgentTokenRoute
  '/api/agente-ia': typeof ApiAgenteIaRoute
  '/api/forms-assistant': typeof ApiFormsAssistantRoute
  '/api/vistoria-chat': typeof ApiVistoriaChatRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/agente-ia': typeof AppAgenteIaRoute
  '/app/agente-perfil': typeof AppAgentePerfilRoute
  '/app/base-conhecimento': typeof AppBaseConhecimentoRoute
  '/app/cases': typeof AppCasesRoute
  '/app/catalogo-materiais': typeof AppCatalogoMateriaisRoute
  '/app/clients': typeof AppClientsRouteWithChildren
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/forms': typeof AppFormsRouteWithChildren
  '/app/forms-assistant': typeof AppFormsAssistantRoute
  '/app/history': typeof AppHistoryRoute
  '/app/minhas-vistorias': typeof AppMinhasVistoriasRoute
  '/app/new-case': typeof AppNewCaseRoute
  '/app/outputs': typeof AppOutputsRoute
  '/app/prompts': typeof AppPromptsRoute
  '/app/review-queue': typeof AppReviewQueueRoute
  '/app/tracking': typeof AppTrackingRoute
  '/app/users': typeof AppUsersRoute
  '/app/agendamento/$id': typeof AppAgendamentoIdRoute
  '/app/clients/$empresaId': typeof AppClientsEmpresaIdRoute
  '/app/review/$id': typeof AppReviewIdRoute
  '/app/vistoria/$casoId': typeof AppVistoriaCasoIdRoute
  '/app/vistorias/$id': typeof AppVistoriasIdRoute
  '/preview/forms/$id': typeof PreviewFormsIdRoute
  '/app/clients/': typeof AppClientsIndexRoute
  '/app/forms/': typeof AppFormsIndexRoute
  '/api/public/hooks/check-atrasos': typeof ApiPublicHooksCheckAtrasosRoute
  '/app/forms/$id/preview': typeof AppFormsIdPreviewRoute
  '/app/forms/$id/': typeof AppFormsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/reset-password'
    | '/agent/$token'
    | '/api/agente-ia'
    | '/api/forms-assistant'
    | '/api/vistoria-chat'
    | '/app/agenda'
    | '/app/agente-ia'
    | '/app/agente-perfil'
    | '/app/base-conhecimento'
    | '/app/cases'
    | '/app/catalogo-materiais'
    | '/app/clients'
    | '/app/configuracoes'
    | '/app/dashboard'
    | '/app/forms'
    | '/app/forms-assistant'
    | '/app/history'
    | '/app/minhas-vistorias'
    | '/app/new-case'
    | '/app/outputs'
    | '/app/prompts'
    | '/app/review-queue'
    | '/app/tracking'
    | '/app/users'
    | '/app/agendamento/$id'
    | '/app/clients/$empresaId'
    | '/app/review/$id'
    | '/app/vistoria/$casoId'
    | '/app/vistorias/$id'
    | '/preview/forms/$id'
    | '/app/clients/'
    | '/app/forms/'
    | '/api/public/hooks/check-atrasos'
    | '/app/forms/$id/preview'
    | '/app/forms/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/reset-password'
    | '/agent/$token'
    | '/api/agente-ia'
    | '/api/forms-assistant'
    | '/api/vistoria-chat'
    | '/app/agenda'
    | '/app/agente-ia'
    | '/app/agente-perfil'
    | '/app/base-conhecimento'
    | '/app/cases'
    | '/app/catalogo-materiais'
    | '/app/configuracoes'
    | '/app/dashboard'
    | '/app/forms-assistant'
    | '/app/history'
    | '/app/minhas-vistorias'
    | '/app/new-case'
    | '/app/outputs'
    | '/app/prompts'
    | '/app/review-queue'
    | '/app/tracking'
    | '/app/users'
    | '/app/agendamento/$id'
    | '/app/clients/$empresaId'
    | '/app/review/$id'
    | '/app/vistoria/$casoId'
    | '/app/vistorias/$id'
    | '/preview/forms/$id'
    | '/app/clients'
    | '/app/forms'
    | '/api/public/hooks/check-atrasos'
    | '/app/forms/$id/preview'
    | '/app/forms/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/reset-password'
    | '/agent/$token'
    | '/api/agente-ia'
    | '/api/forms-assistant'
    | '/api/vistoria-chat'
    | '/app/agenda'
    | '/app/agente-ia'
    | '/app/agente-perfil'
    | '/app/base-conhecimento'
    | '/app/cases'
    | '/app/catalogo-materiais'
    | '/app/clients'
    | '/app/configuracoes'
    | '/app/dashboard'
    | '/app/forms'
    | '/app/forms-assistant'
    | '/app/history'
    | '/app/minhas-vistorias'
    | '/app/new-case'
    | '/app/outputs'
    | '/app/prompts'
    | '/app/review-queue'
    | '/app/tracking'
    | '/app/users'
    | '/app/agendamento/$id'
    | '/app/clients/$empresaId'
    | '/app/review/$id'
    | '/app/vistoria/$casoId'
    | '/app/vistorias/$id'
    | '/preview/forms/$id'
    | '/app/clients/'
    | '/app/forms/'
    | '/api/public/hooks/check-atrasos'
    | '/app/forms/$id/preview'
    | '/app/forms/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  AgentTokenRoute: typeof AgentTokenRoute
  ApiAgenteIaRoute: typeof ApiAgenteIaRoute
  ApiFormsAssistantRoute: typeof ApiFormsAssistantRoute
  ApiVistoriaChatRoute: typeof ApiVistoriaChatRoute
  PreviewFormsIdRoute: typeof PreviewFormsIdRoute
  ApiPublicHooksCheckAtrasosRoute: typeof ApiPublicHooksCheckAtrasosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/users': {
      id: '/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tracking': {
      id: '/app/tracking'
      path: '/tracking'
      fullPath: '/app/tracking'
      preLoaderRoute: typeof AppTrackingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/review-queue': {
      id: '/app/review-queue'
      path: '/review-queue'
      fullPath: '/app/review-queue'
      preLoaderRoute: typeof AppReviewQueueRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/prompts': {
      id: '/app/prompts'
      path: '/prompts'
      fullPath: '/app/prompts'
      preLoaderRoute: typeof AppPromptsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/outputs': {
      id: '/app/outputs'
      path: '/outputs'
      fullPath: '/app/outputs'
      preLoaderRoute: typeof AppOutputsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/new-case': {
      id: '/app/new-case'
      path: '/new-case'
      fullPath: '/app/new-case'
      preLoaderRoute: typeof AppNewCaseRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/minhas-vistorias': {
      id: '/app/minhas-vistorias'
      path: '/minhas-vistorias'
      fullPath: '/app/minhas-vistorias'
      preLoaderRoute: typeof AppMinhasVistoriasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/history': {
      id: '/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/forms-assistant': {
      id: '/app/forms-assistant'
      path: '/forms-assistant'
      fullPath: '/app/forms-assistant'
      preLoaderRoute: typeof AppFormsAssistantRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/forms': {
      id: '/app/forms'
      path: '/forms'
      fullPath: '/app/forms'
      preLoaderRoute: typeof AppFormsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes': {
      id: '/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clients': {
      id: '/app/clients'
      path: '/clients'
      fullPath: '/app/clients'
      preLoaderRoute: typeof AppClientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/catalogo-materiais': {
      id: '/app/catalogo-materiais'
      path: '/catalogo-materiais'
      fullPath: '/app/catalogo-materiais'
      preLoaderRoute: typeof AppCatalogoMateriaisRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cases': {
      id: '/app/cases'
      path: '/cases'
      fullPath: '/app/cases'
      preLoaderRoute: typeof AppCasesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/base-conhecimento': {
      id: '/app/base-conhecimento'
      path: '/base-conhecimento'
      fullPath: '/app/base-conhecimento'
      preLoaderRoute: typeof AppBaseConhecimentoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agente-perfil': {
      id: '/app/agente-perfil'
      path: '/agente-perfil'
      fullPath: '/app/agente-perfil'
      preLoaderRoute: typeof AppAgentePerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agente-ia': {
      id: '/app/agente-ia'
      path: '/agente-ia'
      fullPath: '/app/agente-ia'
      preLoaderRoute: typeof AppAgenteIaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agenda': {
      id: '/app/agenda'
      path: '/agenda'
      fullPath: '/app/agenda'
      preLoaderRoute: typeof AppAgendaRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/vistoria-chat': {
      id: '/api/vistoria-chat'
      path: '/api/vistoria-chat'
      fullPath: '/api/vistoria-chat'
      preLoaderRoute: typeof ApiVistoriaChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/forms-assistant': {
      id: '/api/forms-assistant'
      path: '/api/forms-assistant'
      fullPath: '/api/forms-assistant'
      preLoaderRoute: typeof ApiFormsAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agente-ia': {
      id: '/api/agente-ia'
      path: '/api/agente-ia'
      fullPath: '/api/agente-ia'
      preLoaderRoute: typeof ApiAgenteIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/$token': {
      id: '/agent/$token'
      path: '/agent/$token'
      fullPath: '/agent/$token'
      preLoaderRoute: typeof AgentTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/forms/': {
      id: '/app/forms/'
      path: '/'
      fullPath: '/app/forms/'
      preLoaderRoute: typeof AppFormsIndexRouteImport
      parentRoute: typeof AppFormsRoute
    }
    '/app/clients/': {
      id: '/app/clients/'
      path: '/'
      fullPath: '/app/clients/'
      preLoaderRoute: typeof AppClientsIndexRouteImport
      parentRoute: typeof AppClientsRoute
    }
    '/preview/forms/$id': {
      id: '/preview/forms/$id'
      path: '/preview/forms/$id'
      fullPath: '/preview/forms/$id'
      preLoaderRoute: typeof PreviewFormsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/vistorias/$id': {
      id: '/app/vistorias/$id'
      path: '/vistorias/$id'
      fullPath: '/app/vistorias/$id'
      preLoaderRoute: typeof AppVistoriasIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vistoria/$casoId': {
      id: '/app/vistoria/$casoId'
      path: '/vistoria/$casoId'
      fullPath: '/app/vistoria/$casoId'
      preLoaderRoute: typeof AppVistoriaCasoIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/review/$id': {
      id: '/app/review/$id'
      path: '/review/$id'
      fullPath: '/app/review/$id'
      preLoaderRoute: typeof AppReviewIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clients/$empresaId': {
      id: '/app/clients/$empresaId'
      path: '/$empresaId'
      fullPath: '/app/clients/$empresaId'
      preLoaderRoute: typeof AppClientsEmpresaIdRouteImport
      parentRoute: typeof AppClientsRoute
    }
    '/app/agendamento/$id': {
      id: '/app/agendamento/$id'
      path: '/agendamento/$id'
      fullPath: '/app/agendamento/$id'
      preLoaderRoute: typeof AppAgendamentoIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/forms/$id/': {
      id: '/app/forms/$id/'
      path: '/$id'
      fullPath: '/app/forms/$id/'
      preLoaderRoute: typeof AppFormsIdIndexRouteImport
      parentRoute: typeof AppFormsRoute
    }
    '/app/forms/$id/preview': {
      id: '/app/forms/$id/preview'
      path: '/$id/preview'
      fullPath: '/app/forms/$id/preview'
      preLoaderRoute: typeof AppFormsIdPreviewRouteImport
      parentRoute: typeof AppFormsRoute
    }
    '/api/public/hooks/check-atrasos': {
      id: '/api/public/hooks/check-atrasos'
      path: '/api/public/hooks/check-atrasos'
      fullPath: '/api/public/hooks/check-atrasos'
      preLoaderRoute: typeof ApiPublicHooksCheckAtrasosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppClientsRouteChildren {
  AppClientsEmpresaIdRoute: typeof AppClientsEmpresaIdRoute
  AppClientsIndexRoute: typeof AppClientsIndexRoute
}

const AppClientsRouteChildren: AppClientsRouteChildren = {
  AppClientsEmpresaIdRoute: AppClientsEmpresaIdRoute,
  AppClientsIndexRoute: AppClientsIndexRoute,
}

const AppClientsRouteWithChildren = AppClientsRoute._addFileChildren(
  AppClientsRouteChildren,
)

interface AppFormsRouteChildren {
  AppFormsIndexRoute: typeof AppFormsIndexRoute
  AppFormsIdPreviewRoute: typeof AppFormsIdPreviewRoute
  AppFormsIdIndexRoute: typeof AppFormsIdIndexRoute
}

const AppFormsRouteChildren: AppFormsRouteChildren = {
  AppFormsIndexRoute: AppFormsIndexRoute,
  AppFormsIdPreviewRoute: AppFormsIdPreviewRoute,
  AppFormsIdIndexRoute: AppFormsIdIndexRoute,
}

const AppFormsRouteWithChildren = AppFormsRoute._addFileChildren(
  AppFormsRouteChildren,
)

interface AppRouteChildren {
  AppAgendaRoute: typeof AppAgendaRoute
  AppAgenteIaRoute: typeof AppAgenteIaRoute
  AppAgentePerfilRoute: typeof AppAgentePerfilRoute
  AppBaseConhecimentoRoute: typeof AppBaseConhecimentoRoute
  AppCasesRoute: typeof AppCasesRoute
  AppCatalogoMateriaisRoute: typeof AppCatalogoMateriaisRoute
  AppClientsRoute: typeof AppClientsRouteWithChildren
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFormsRoute: typeof AppFormsRouteWithChildren
  AppFormsAssistantRoute: typeof AppFormsAssistantRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppMinhasVistoriasRoute: typeof AppMinhasVistoriasRoute
  AppNewCaseRoute: typeof AppNewCaseRoute
  AppOutputsRoute: typeof AppOutputsRoute
  AppPromptsRoute: typeof AppPromptsRoute
  AppReviewQueueRoute: typeof AppReviewQueueRoute
  AppTrackingRoute: typeof AppTrackingRoute
  AppUsersRoute: typeof AppUsersRoute
  AppAgendamentoIdRoute: typeof AppAgendamentoIdRoute
  AppReviewIdRoute: typeof AppReviewIdRoute
  AppVistoriaCasoIdRoute: typeof AppVistoriaCasoIdRoute
  AppVistoriasIdRoute: typeof AppVistoriasIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgendaRoute: AppAgendaRoute,
  AppAgenteIaRoute: AppAgenteIaRoute,
  AppAgentePerfilRoute: AppAgentePerfilRoute,
  AppBaseConhecimentoRoute: AppBaseConhecimentoRoute,
  AppCasesRoute: AppCasesRoute,
  AppCatalogoMateriaisRoute: AppCatalogoMateriaisRoute,
  AppClientsRoute: AppClientsRouteWithChildren,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFormsRoute: AppFormsRouteWithChildren,
  AppFormsAssistantRoute: AppFormsAssistantRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppMinhasVistoriasRoute: AppMinhasVistoriasRoute,
  AppNewCaseRoute: AppNewCaseRoute,
  AppOutputsRoute: AppOutputsRoute,
  AppPromptsRoute: AppPromptsRoute,
  AppReviewQueueRoute: AppReviewQueueRoute,
  AppTrackingRoute: AppTrackingRoute,
  AppUsersRoute: AppUsersRoute,
  AppAgendamentoIdRoute: AppAgendamentoIdRoute,
  AppReviewIdRoute: AppReviewIdRoute,
  AppVistoriaCasoIdRoute: AppVistoriaCasoIdRoute,
  AppVistoriasIdRoute: AppVistoriasIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  AgentTokenRoute: AgentTokenRoute,
  ApiAgenteIaRoute: ApiAgenteIaRoute,
  ApiFormsAssistantRoute: ApiFormsAssistantRoute,
  ApiVistoriaChatRoute: ApiVistoriaChatRoute,
  PreviewFormsIdRoute: PreviewFormsIdRoute,
  ApiPublicHooksCheckAtrasosRoute: ApiPublicHooksCheckAtrasosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
