/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUsersRouteImport } from './routes/app.users'
import { Route as AppTrackingRouteImport } from './routes/app.tracking'
import { Route as AppReviewQueueRouteImport } from './routes/app.review-queue'
import { Route as AppPromptsRouteImport } from './routes/app.prompts'
import { Route as AppOutputsRouteImport } from './routes/app.outputs'
import { Route as AppNewCaseRouteImport } from './routes/app.new-case'
import { Route as AppHistoryRouteImport } from './routes/app.history'
import { Route as AppFormsRouteImport } from './routes/app.forms'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppClientsRouteImport } from './routes/app.clients'
import { Route as AppCasesRouteImport } from './routes/app.cases'
import { Route as AgentTokenRouteImport } from './routes/agent.$token'
import { Route as AppFormsIndexRouteImport } from './routes/app.forms.index'
import { Route as AppReviewIdRouteImport } from './routes/app.review.$id'
import { Route as AppFormsIdRouteImport } from './routes/app.forms.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppTrackingRoute = AppTrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewQueueRoute = AppReviewQueueRouteImport.update({
  id: '/review-queue',
  path: '/review-queue',
  getParentRoute: () => AppRoute,
} as any)
const AppPromptsRoute = AppPromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => AppRoute,
} as any)
const AppOutputsRoute = AppOutputsRouteImport.update({
  id: '/outputs',
  path: '/outputs',
  getParentRoute: () => AppRoute,
} as any)
const AppNewCaseRoute = AppNewCaseRouteImport.update({
  id: '/new-case',
  path: '/new-case',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppFormsRoute = AppFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsRoute = AppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppRoute,
} as any)
const AppCasesRoute = AppCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => AppRoute,
} as any)
const AgentTokenRoute = AgentTokenRouteImport.update({
  id: '/agent/$token',
  path: '/agent/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppFormsIndexRoute = AppFormsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppFormsRoute,
} as any)
const AppReviewIdRoute = AppReviewIdRouteImport.update({
  id: '/review/$id',
  path: '/review/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppFormsIdRoute = AppFormsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppFormsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/agent/$token': typeof AgentTokenRoute
  '/app/cases': typeof AppCasesRoute
  '/app/clients': typeof AppClientsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/forms': typeof AppFormsRouteWithChildren
  '/app/history': typeof AppHistoryRoute
  '/app/new-case': typeof AppNewCaseRoute
  '/app/outputs': typeof AppOutputsRoute
  '/app/prompts': typeof AppPromptsRoute
  '/app/review-queue': typeof AppReviewQueueRoute
  '/app/tracking': typeof AppTrackingRoute
  '/app/users': typeof AppUsersRoute
  '/app/forms/$id': typeof AppFormsIdRoute
  '/app/review/$id': typeof AppReviewIdRoute
  '/app/forms/': typeof AppFormsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/agent/$token': typeof AgentTokenRoute
  '/app/cases': typeof AppCasesRoute
  '/app/clients': typeof AppClientsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/history': typeof AppHistoryRoute
  '/app/new-case': typeof AppNewCaseRoute
  '/app/outputs': typeof AppOutputsRoute
  '/app/prompts': typeof AppPromptsRoute
  '/app/review-queue': typeof AppReviewQueueRoute
  '/app/tracking': typeof AppTrackingRoute
  '/app/users': typeof AppUsersRoute
  '/app/forms/$id': typeof AppFormsIdRoute
  '/app/review/$id': typeof AppReviewIdRoute
  '/app/forms': typeof AppFormsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/agent/$token': typeof AgentTokenRoute
  '/app/cases': typeof AppCasesRoute
  '/app/clients': typeof AppClientsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/forms': typeof AppFormsRouteWithChildren
  '/app/history': typeof AppHistoryRoute
  '/app/new-case': typeof AppNewCaseRoute
  '/app/outputs': typeof AppOutputsRoute
  '/app/prompts': typeof AppPromptsRoute
  '/app/review-queue': typeof AppReviewQueueRoute
  '/app/tracking': typeof AppTrackingRoute
  '/app/users': typeof AppUsersRoute
  '/app/forms/$id': typeof AppFormsIdRoute
  '/app/review/$id': typeof AppReviewIdRoute
  '/app/forms/': typeof AppFormsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/reset-password'
    | '/agent/$token'
    | '/app/cases'
    | '/app/clients'
    | '/app/dashboard'
    | '/app/forms'
    | '/app/history'
    | '/app/new-case'
    | '/app/outputs'
    | '/app/prompts'
    | '/app/review-queue'
    | '/app/tracking'
    | '/app/users'
    | '/app/forms/$id'
    | '/app/review/$id'
    | '/app/forms/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/reset-password'
    | '/agent/$token'
    | '/app/cases'
    | '/app/clients'
    | '/app/dashboard'
    | '/app/history'
    | '/app/new-case'
    | '/app/outputs'
    | '/app/prompts'
    | '/app/review-queue'
    | '/app/tracking'
    | '/app/users'
    | '/app/forms/$id'
    | '/app/review/$id'
    | '/app/forms'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/reset-password'
    | '/agent/$token'
    | '/app/cases'
    | '/app/clients'
    | '/app/dashboard'
    | '/app/forms'
    | '/app/history'
    | '/app/new-case'
    | '/app/outputs'
    | '/app/prompts'
    | '/app/review-queue'
    | '/app/tracking'
    | '/app/users'
    | '/app/forms/$id'
    | '/app/review/$id'
    | '/app/forms/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  AgentTokenRoute: typeof AgentTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/users': {
      id: '/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tracking': {
      id: '/app/tracking'
      path: '/tracking'
      fullPath: '/app/tracking'
      preLoaderRoute: typeof AppTrackingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/review-queue': {
      id: '/app/review-queue'
      path: '/review-queue'
      fullPath: '/app/review-queue'
      preLoaderRoute: typeof AppReviewQueueRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/prompts': {
      id: '/app/prompts'
      path: '/prompts'
      fullPath: '/app/prompts'
      preLoaderRoute: typeof AppPromptsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/outputs': {
      id: '/app/outputs'
      path: '/outputs'
      fullPath: '/app/outputs'
      preLoaderRoute: typeof AppOutputsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/new-case': {
      id: '/app/new-case'
      path: '/new-case'
      fullPath: '/app/new-case'
      preLoaderRoute: typeof AppNewCaseRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/history': {
      id: '/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/forms': {
      id: '/app/forms'
      path: '/forms'
      fullPath: '/app/forms'
      preLoaderRoute: typeof AppFormsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clients': {
      id: '/app/clients'
      path: '/clients'
      fullPath: '/app/clients'
      preLoaderRoute: typeof AppClientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cases': {
      id: '/app/cases'
      path: '/cases'
      fullPath: '/app/cases'
      preLoaderRoute: typeof AppCasesRouteImport
      parentRoute: typeof AppRoute
    }
    '/agent/$token': {
      id: '/agent/$token'
      path: '/agent/$token'
      fullPath: '/agent/$token'
      preLoaderRoute: typeof AgentTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/forms/': {
      id: '/app/forms/'
      path: '/'
      fullPath: '/app/forms/'
      preLoaderRoute: typeof AppFormsIndexRouteImport
      parentRoute: typeof AppFormsRoute
    }
    '/app/review/$id': {
      id: '/app/review/$id'
      path: '/review/$id'
      fullPath: '/app/review/$id'
      preLoaderRoute: typeof AppReviewIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/forms/$id': {
      id: '/app/forms/$id'
      path: '/$id'
      fullPath: '/app/forms/$id'
      preLoaderRoute: typeof AppFormsIdRouteImport
      parentRoute: typeof AppFormsRoute
    }
  }
}

interface AppFormsRouteChildren {
  AppFormsIdRoute: typeof AppFormsIdRoute
  AppFormsIndexRoute: typeof AppFormsIndexRoute
}

const AppFormsRouteChildren: AppFormsRouteChildren = {
  AppFormsIdRoute: AppFormsIdRoute,
  AppFormsIndexRoute: AppFormsIndexRoute,
}

const AppFormsRouteWithChildren = AppFormsRoute._addFileChildren(
  AppFormsRouteChildren,
)

interface AppRouteChildren {
  AppCasesRoute: typeof AppCasesRoute
  AppClientsRoute: typeof AppClientsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFormsRoute: typeof AppFormsRouteWithChildren
  AppHistoryRoute: typeof AppHistoryRoute
  AppNewCaseRoute: typeof AppNewCaseRoute
  AppOutputsRoute: typeof AppOutputsRoute
  AppPromptsRoute: typeof AppPromptsRoute
  AppReviewQueueRoute: typeof AppReviewQueueRoute
  AppTrackingRoute: typeof AppTrackingRoute
  AppUsersRoute: typeof AppUsersRoute
  AppReviewIdRoute: typeof AppReviewIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCasesRoute: AppCasesRoute,
  AppClientsRoute: AppClientsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFormsRoute: AppFormsRouteWithChildren,
  AppHistoryRoute: AppHistoryRoute,
  AppNewCaseRoute: AppNewCaseRoute,
  AppOutputsRoute: AppOutputsRoute,
  AppPromptsRoute: AppPromptsRoute,
  AppReviewQueueRoute: AppReviewQueueRoute,
  AppTrackingRoute: AppTrackingRoute,
  AppUsersRoute: AppUsersRoute,
  AppReviewIdRoute: AppReviewIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  AgentTokenRoute: AgentTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
